<?php
// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) :
    exit;
endif;

return apply_filters( 'mcwc_country_by_currency', array(
    'US' => 'USD',
    'IN' => 'INR',
    'GB' => 'GBP',
    'CA' => 'CAD',
    'AU' => 'AUD',
    'NZ' => 'NZD',
    'JP' => 'JPY',
    'CN' => 'CNY',
    'SG' => 'SGD',
    'HK' => 'HKD',
    'EU' => 'EUR',
    'DE' => 'EUR',
    'FR' => 'EUR',
    'IT' => 'EUR',
    'ES' => 'EUR',
    'NL' => 'EUR',
    'BE' => 'EUR',
    'AT' => 'EUR',
    'IE' => 'EUR',
    'FI' => 'EUR',
    'GR' => 'EUR',
    'PT' => 'EUR',
    'LU' => 'EUR',
    'CY' => 'EUR',
    'MT' => 'EUR',
    'AE' => 'AED',
    'SA' => 'SAR',
    'QA' => 'QAR',
    'OM' => 'OMR',
    'KW' => 'KWD',
    'BH' => 'BHD',
    'VN' => 'VND',
    'TH' => 'THB',
    'MY' => 'MYR',
    'ID' => 'IDR',
    'PH' => 'PHP',
    'BD' => 'BDT',
    'PK' => 'PKR',
    'LK' => 'LKR',
    'NP' => 'NPR',
    'IR' => 'IRR',
    'IQ' => 'IQD',
    'IL' => 'ILS',
    'RU' => 'RUB',
    'UA' => 'UAH',
    'ZA' => 'ZAR',
    'NG' => 'NGN',
    'KE' => 'KES',
    'TZ' => 'TZS',
    'UG' => 'UGX',
    'GH' => 'GHS',
    'ZM' => 'ZMW',
    'MX' => 'MXN',
    'BR' => 'BRL',
    'AR' => 'ARS',
    'CL' => 'CLP',
    'CO' => 'COP',
    'PE' => 'PEN',
    'VE' => 'VES',
    'UY' => 'UYU',
    'BO' => 'BOB',
    'PY' => 'PYG',
    'CU' => 'CUP',
    'JM' => 'JMD',
    'TT' => 'TTD',
    'AG' => 'XCD',
    'BB' => 'BBD',
    'BZ' => 'BZD',
    'DM' => 'XCD',
    'GD' => 'XCD',
    'LC' => 'XCD',
    'KN' => 'XCD',
    'VC' => 'XCD',
    'CR' => 'CRC',
    'PA' => 'PAB',
    'HN' => 'HNL',
    'GT' => 'GTQ',
    'SV' => 'USD',
    'DO' => 'DOP'
) );
