<?php 
return apply_filters( 'mcwc_get_default_options',
    array(
        'enable'                        => 'yes',
        'fixed_price'                   => 'no',
        'use_session'                   => 'yes',
        'switch_currency_by_js'         => 'no',
        'use_cache'                     => 'none',
        'currencies'                    => [],
        'auto_detect'                   => 'auto_select',
        'approx_price_label'            => 'Estimated: ~ {converted_price}',
        'approx_price_position'         => 'below',
        'switch_user_login'             => 'billing_then_shipping',
        'currency_by_country'           => 'yes',
        'change_currency_follow'        => 'no',
        'sync_checkout_currency'        => 'no',
        'only_shipping_country'         => 'no',
        'switcher_title'                => 'Select your currency',
        'design_position'               => 'right',
        'enable_desktop'                => 'no',
        'expand_button_color'           => '#000000',
        'expand_button_bg'              => '#ffffff',
        'expand_button_opacity'         => '1',
        'text_color'                    => '#ffffff',
        'sidebar_style'                 => 'default',
        'hover_color'                   => '#e67e00',
        'background_color'              => '#dd9933',
        'single_switcher_style'         => 'no',
        'switcher_layout'               => 'split',
        'single_position'               => 'woocommerce_before_add_to_cart_button-10',
        'shortcode_color'               => '#212121',
        'shortcode_bg_color'            => '#ffffff',
        'shortcode_active_color'        => '#212121',
        'shortcode_active_bg_color'     => '#ffffff',
        'custom_flag'                   => '',
        'rel_nofollow'                  => 'no',
        'custom_css'                    => '',
        'hide_on_home'                  => 'no',
        'hide_on_shop'                  => 'no',
        'hide_on_single_product'        => 'no',
        'hide_on_cart'                  => 'no',
        'hide_on_checkout'              => 'no',
        'hide_on_product_category'      => 'no',
        'conditional_tags'              => '',
        'enable_auto_update_exchange'   => 'no',
        'update_exchange_interval'      => 720,
        'finance_api'                   => 'google',
        'wise_api_token'                => '',
        'openexchangerates_app_id'      => '',
        'exchangeratesapi_key'          => '',
        'currencyapi_key'               => '',
        'rate_decimals'                 => 5,
        'enable_send_email'             => 'yes',
        'email_custom'                  => '',
    )
);